# https://taskfile.dev/docs/guide
version: '3'

tasks:
  default:
    cmds:
      - task -l
  app:build:
    desc: build the application
    cmds:
      - go build -o bin/diveLog cmd/main.go
  app:run:
    desc: run the application
    aliases: [app]
    deps: [app:build]
    cmds:
      - ./bin/diveLog