# https://taskfile.dev/docs/guide
version: "3"

tasks:
  default:
    cmds:
      - task -l
  app:clean:
    desc: remove existing binaries
    cmds:
      - rm -f bin/*
  app:build:
    desc: build the application
    deps: [app:clean]
    cmds:
      - go build -o bin/divelog cmd/divelog/main.go
  app:run:
    desc: run the application
    aliases: [app]
    deps: [app:build]
    cmds:
      - ./bin/divelog
  image:build:
    desc: build the application as a docker image
    cmds:
      - docker build -t ghcr.io/kiarrobino/divelog:local -t ghcr.io/kiarrobino/divelog:latest .
  image:run:
    desc: run the application as docker image
    aliases: [image]
    deps: [image:build]
    cmds:
      - docker run --name divelog -it -d -p 8080:8080 -v $(pwd)/data:/app/data -e DB_PATH=/app/data/divelog.db divelog:local
  k8s:deploy:
    desc: run the application in a local kubernetes cluster
    aliases: [up]
    deps: [image:build]
    cmds:
      - kind create cluster --name divelog
      - kind load docker-image ghcr.io/kiarrobino/divelog:latest --name divelog
      - helm install monitoring prometheus-community/kube-prometheus-stack --namespace monitoring --create-namespace
      - helm install divelog ./helm/divelog
  k8s:upgrade:
    desc: deploy latest version of application to already running local kubernetes cluster
    aliases: [upgrade]
    deps: [image:build]
    cmds:
      - kind load docker-image ghcr.io/kiarrobino/divelog:latest --name divelog
      - helm upgrade divelog ./helm/divelog
  k8s:db:backup:
    desc: run script to backup the local kubernetes cluster database
    cmds:
      - mkdir -p data/backups
      - bash scripts/backup.sh
  k8s:db:restore:
    desc: restore local kubernetes cluster database from backup
    cmds:
      - kubectl cp {{.FILE}} $(kubectl get pods -l app.kubernetes.io/name=divelog -o jsonpath="{.items[0].metadata.name}"):/app/data/divelog.db
      - kubectl rollout restart deploy/divelog
  k8s:teardown:
    desc: stop the local kubernetes cluster
    aliases: [down]
    cmds:
      - kind delete cluster --name divelog
  test:unit:
    desc: run the application unit tests
    aliases: [test]
    cmds:
      - go test ./... -coverprofile=coverage.out -v
      - go tool cover -func=coverage.out
  db:clean:
    desc: remove all existing database backups
      - rm -f data/backups/*
