apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "divelog.fullname" . }}
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: divelog
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /api/metrics
      interval: 15s